import {
    Eye,
    Globe,
    Leaf as LeafIcon,
    Lightbulb,
    Lock,
    Rocket,
    Sparkles,
    Target,
    ShieldCheck,
    BarChart3,
    Cpu,
    GraduationCap,
    Layers,
    Check,
    ArrowRight,
    Star,
    Filter,
    Package,
    Network,
    ExternalLink,
    EyeIcon,
    EyeClosed,
    ArrowLeft,
    Search,
    ShieldUser,
    LayoutDashboard,
    CalendarsIcon,
    UsersRound,
    MonitorCloudIcon,
    UsersRoundIcon,
    SlidersVerticalIcon,
    FolderCodeIcon,
    Trash2Icon,
    SquarePenIcon,
    ChevronLeftIcon,
    ChevronRightIcon
} from 'lucide-react'
import { RiGlobalFill, RiInstagramFill } from "react-icons/ri";
import { IoLogoWhatsapp } from 'react-icons/io'
import { LuLeaf, LuUsers } from 'react-icons/lu'
import { FaFacebookF, FaLinkedin, FaInstagram, FaGithub, FaTiktok, FaAnglesRight } from "react-icons/fa6";
import { AiOutlineFilePdf } from 'react-icons/ai';
import { FaSignInAlt } from 'react-icons/fa';
import { PiSignIn } from 'react-icons/pi';
import { FiLogOut } from 'react-icons/fi';
import { CiMenuFries } from 'react-icons/ci';

const Icon = {
    IoLogoWhatsapp,
    LuUsers,
    Sparkles,
    Target,
    LuLeaf,
    Eye,
    Rocket,
    FaFacebookF,
    Lock,
    Lightbulb,
    Globe,
    FaLinkedin,
    Leaf: LeafIcon,
    FaInstagram,
    FaGithub,
    ShieldCheck,
    BarChart3,
    Cpu,
    GraduationCap,
    Layers,
    Check,
    ArrowRight,
    Star,
    Filter,
    Package,
    RiGlobalFill,
    Network,
    FaTiktok,
    RiInstagramFill,
    ExternalLink,
    AiOutlineFilePdf,
    FaSignInAlt,
    PiSignIn,
    EyeIcon,
    EyeClosed,
    ArrowLeft,
    Search,
    ShieldUser,
    LayoutDashboard,
    CalendarsIcon,
    UsersRoundIcon,
    MonitorCloudIcon,
    SlidersVerticalIcon,
    FolderCodeIcon,
    Trash2Icon,
    SquarePenIcon,
    FiLogOut,
    CiMenuFries,
    FaAnglesRight,
    ChevronLeftIcon,
    ChevronRightIcon
}

export default Icon